#%RAML 1.0
title: uhub-sapi
version: v1
baseUri: http://uho-ntpldev-uhub-sapi.us-e2.cloudhub.io/covid/v1
traits:
  client-id-header: !include exchange_modules/286e56fb-8f93-4454-83f5-6ef1e2a38ce1/client-id-required/1.0.0/client-id-required.raml
  transaction-header: !include exchange_modules/286e56fb-8f93-4454-83f5-6ef1e2a38ce1/transaction-header/1.0.0/transaction-header.raml
  correlation-id-header: !include exchange_modules/286e56fb-8f93-4454-83f5-6ef1e2a38ce1/correlation-id-header/1.0.0/correlation-id-header.raml
  state-query-param: !include uhub-sapi-types/state-query-param.raml

uses:
  uhub-sapi-types: uhub-sapi-types/uhub-sapi-types.raml
  common-data-types: exchange_modules/286e56fb-8f93-4454-83f5-6ef1e2a38ce1/common-data-types/1.0.0/common-data-types.raml
  resource-types: exchange_modules/286e56fb-8f93-4454-83f5-6ef1e2a38ce1/resource-types/1.0.0/resource-types.raml


/cases:
  description: To register covid cases
  post:
    is: [client-id-header,transaction-header,correlation-id-header]      
    body:
      application/json:
        type: uhub-sapi-types.covid-case-request-type
        example: !include examples/covid-case-request.json
    responses:
      200:
        body:
          application/json:
            type: uhub-sapi-types.covid-case-response-type
            example: !include examples/covid-case-response.json
      400:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/400.json
      500:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/500.json
      503:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/503.json
  put:
    description: To update covid cases
    is: [client-id-header,transaction-header,correlation-id-header]      
    body:
      application/json:
        type: uhub-sapi-types.covid-case-update-request-type
        example: !include examples/covid-case-update-request.json
    responses:
      200:
        body:
          application/json:
            type: uhub-sapi-types.covid-case-update-response-type
            example: !include examples/covid-case-update-response.json
      400:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/400.json
      500:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/500.json
      503:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/503.json
  /{nationalID}:
    get:
      description: To get covid case by national id.
      is: [client-id-header,transaction-header,correlation-id-header]
      responses:
        200:
          body:
            application/json:
              type: uhub-sapi-types.get-cases-by-national-id-response-type
              example: !include examples/get-cases-by-national-id-response.json
        404:
          body:
            application/json:
              type: common-data-types.errorType
              example: !include examples/404.json
        500:
          body:
            application/json:
              type: common-data-types.errorType
              example: !include examples/500.json
        503:
          body:
            application/json:
              type: common-data-types.errorType
              example: !include examples/503.json
/reports:
  get:
    description: To get covid reports
    is: [client-id-header,transaction-header,correlation-id-header,state-query-param]
    responses:
      200:
        body:
          application/json:
            type: uhub-sapi-types.get-reports-response-type
            example: !include examples/get-reports-response.json
      404:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/404.json
      500:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/500.json
      503:
        body:
          application/json:
            type: common-data-types.errorType
            example: !include examples/503.json
/health-check:
  get:
  type:
    resource-types.all:
      getResponseType: string
   
  
              
            



     
  

              
          
        